name: Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on push to main branch, adjust if needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to Shared Hosting
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.raonikeshnk.in  # FTP server address
        username: ${{ secrets.FTP_USERNAME }}  # FTP username (store in GitHub secrets)
        password: ${{ secrets.FTP_PASSWORD }}  # FTP password (store in GitHub secrets)
        port: 21  # FTP port
        protocol: ftp  # Use FTP method
        local-dir: ./build/  # Path to the build directory
        server-dir: /  # Remote directory on the server